import httpx
import pandas as pd
import streamlit as st

from frontend.api import stream_chat_question
from frontend.charts import render_chart_spec, render_distribution_chart


# ═══════════════════════════════════════════════════════════════════════════════
# TAB 1: DASHBOARD
# ═══════════════════════════════════════════════════════════════════════════════


def render_dashboard_tab(
    profile: dict[str, object],
    auto_analysis: dict[str, object],
    suggestions: dict[str, object],
) -> None:
    ai_status = auto_analysis.get("ai_status", {})
    if ai_status:
        if ai_status.get("used"):
            st.markdown(
                "✨ **AI Analysis Active**: Insights generated by the LLM planner."
            )
        elif ai_status.get("error"):
            st.warning(
                f"⚠️ **AI Fallback Mode**: {ai_status.get('error')} Using built-in statistics instead."
            )
        elif ai_status.get("mode") != "deterministic":
            st.info(
                "ℹ️ **Offline Mode**: AI key not provided. Using built-in statistics."
            )

    overview = auto_analysis.get("overview", {})
    quality = auto_analysis.get("data_quality", {})

    rows = overview.get("rows", profile.get("rows", 0))
    columns = overview.get("columns", profile.get("columns", 0))
    missing_cells = quality.get("total_missing_cells", 0)
    chart_count = len(auto_analysis.get("recommended_charts", []))

    # ── Metric Cards ──────────────────────────────────────────────────────
    st.markdown(
        f"""
        <div class="metric-container">
            <div class="custom-card">
                <div class="card-label">📁 Rows</div>
                <div class="card-value">{rows:,}</div>
            </div>
            <div class="custom-card">
                <div class="card-label">📊 Columns</div>
                <div class="card-value">{columns}</div>
            </div>
            <div class="custom-card">
                <div class="card-label">⚠️ Missing Cells</div>
                <div class="card-value">{missing_cells:,}</div>
            </div>
            <div class="custom-card">
                <div class="card-label">📈 Recommended Charts</div>
                <div class="card-value">{chart_count}</div>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    # ── Visual Analysis (Charts) — DISPLAYED FIRST as user requested ──────
    charts = auto_analysis.get("recommended_charts", [])
    dataset_frame = st.session_state.get("dataset_frame")
    if charts and isinstance(dataset_frame, pd.DataFrame):
        st.markdown("### 📊 Visual Analysis")
        for i in range(0, len(charts[:4]), 2):
            chart_columns = st.columns(2)
            for j in range(2):
                if i + j < len(charts[:4]):
                    item = charts[i + j]
                    with chart_columns[j]:
                        spec = item.get("chart_spec")
                        if isinstance(spec, dict):
                            spec_copy = dict(spec)
                            if "title" in item:
                                spec_copy["title"] = item.get("title")
                            render_chart_spec(
                                dataset_frame,
                                spec_copy,
                                chart_key=f"dashboard-main-chart-{i+j}",
                            )
                        st.caption(str(item.get("reason", "")))

    # ── Key Insights + Data Quality ───────────────────────────────────────
    story_col, quality_col = st.columns([1.25, 1])
    with story_col:
        st.markdown("### 💡 Key Insights")
        insight_items = _dashboard_insight_items(auto_analysis, suggestions)
        if not insight_items:
            st.info("No insight highlights available yet.")
        else:
            for insight in insight_items:
                st.markdown(
                    f"""
                    <div class="insight-item">
                        <span class="insight-icon">✨</span>
                        <div class="insight-text">{insight}</div>
                    </div>
                    """,
                    unsafe_allow_html=True,
                )

    with quality_col:
        st.markdown("### 🔍 Data Quality")
        missing = pd.DataFrame(quality.get("top_missing_columns", []))
        if missing.empty:
            st.markdown(
                """
                <div class="custom-alert-success">
                    <span style="font-size: 20px;">✨</span>
                    <span>No missing values detected. All columns are fully populated!</span>
                </div>
                """,
                unsafe_allow_html=True,
            )
        else:
            st.dataframe(
                missing[["name", "missing_count", "missing_percent"]],
                use_container_width=True,
                hide_index=True,
            )

    # ── How the dashboard was generated ───────────────────────────────────
    with st.expander("How the dashboard was generated", expanded=False):
        _render_dataset_analysis_activity(auto_analysis, profile)


# ═══════════════════════════════════════════════════════════════════════════════
# TAB 2: DATA EXPLORER
# ═══════════════════════════════════════════════════════════════════════════════


def render_data_explorer_tab(profile: dict[str, object]) -> None:
    preview_tab, schema_tab, stats_tab, dist_tab = st.tabs(
        [
            "📋 Preview",
            "🏗️ Schema",
            "📈 Statistics",
            "📊 Distributions",
        ]
    )

    with preview_tab:
        preview_data = profile.get("preview", [])
        if preview_data:
            st.dataframe(
                pd.DataFrame(preview_data),
                use_container_width=True,
                hide_index=True,
            )
        else:
            st.info("No preview data available.")

    with schema_tab:
        dtypes = profile.get("dtypes", [])
        if dtypes:
            st.dataframe(
                pd.DataFrame(dtypes),
                use_container_width=True,
                hide_index=True,
            )
        else:
            st.info("No schema information available.")

    with stats_tab:
        # ── Numeric Summary ───────────────────────────────────────────
        st.markdown(
            '<div class="stat-section-title">🔢 Numeric Summary</div>',
            unsafe_allow_html=True,
        )
        numeric_summary = pd.DataFrame(profile.get("numeric_summary", []))
        if numeric_summary.empty:
            st.info("No numeric columns detected.")
        else:
            st.dataframe(numeric_summary, use_container_width=True, hide_index=True)

        # ── Categorical Highlights ────────────────────────────────────
        st.markdown(
            '<div class="stat-section-title">🏷️ Categorical Highlights</div>',
            unsafe_allow_html=True,
        )
        top_categories = profile.get("top_categories", [])
        if not top_categories:
            st.info("No categorical columns detected.")
        else:
            for item in top_categories:
                st.write(f"Top values for `{item['column']}`")
                st.dataframe(
                    pd.DataFrame(item["values"]),
                    use_container_width=True,
                    hide_index=True,
                )

        # ── Missing Values ────────────────────────────────────────────
        st.markdown(
            '<div class="stat-section-title">⚠️ Missing Values</div>',
            unsafe_allow_html=True,
        )
        missing = pd.DataFrame(profile.get("missing_values", []))
        if missing.empty:
            st.success("No missing values detected.")
        else:
            st.dataframe(missing, use_container_width=True, hide_index=True)

    with dist_tab:
        distributions = profile.get("distributions", [])
        if not distributions:
            st.info("No distribution charts available.")
        else:
            # 2-column grid for distributions
            for i in range(0, len(distributions), 2):
                dist_cols = st.columns(2)
                for j in range(2):
                    if i + j < len(distributions):
                        spec = distributions[i + j]
                        with dist_cols[j]:
                            st.write(f"`{spec['column']}`")
                            render_distribution_chart(
                                spec,
                                chart_key=f"explorer-dist-{i+j}-{spec['column']}",
                            )


# ═══════════════════════════════════════════════════════════════════════════════
# TAB 3: CHAT
# ═══════════════════════════════════════════════════════════════════════════════


def render_chat_tab(
    auto_analysis: dict[str, object],
    suggestions: dict[str, object],
) -> None:
    # ── Suggested Questions (moved here from old "Ask next" tab) ──────────
    questions = _dedupe_texts(
        [str(item) for item in auto_analysis.get("next_questions", [])]
        + [str(item) for item in suggestions.get("questions", [])]
    )
    if questions:
        st.markdown("#### 💡 Suggested Questions")
        question_cols = st.columns(2)
        for index, question_item in enumerate(questions[:6]):
            with question_cols[index % 2]:
                if st.button(
                    question_item,
                    key=f"chat-question-{index}",
                    use_container_width=True,
                ):
                    st.session_state.pending_chat_question = question_item
                    st.rerun()
        st.markdown("---")

    # ── Chat Messages ─────────────────────────────────────────────────────
    if "chat_messages" not in st.session_state:
        st.session_state.chat_messages = []

    for index, message in enumerate(st.session_state.chat_messages):
        with st.chat_message(message["role"]):
            st.write(message["content"])
            render_chat_artifacts(message, message_index=index)

    # ── Chat Input ────────────────────────────────────────────────────────
    pending_question = st.session_state.pop("pending_chat_question", None)
    typed_question = st.chat_input("Ask a question about the uploaded dataset")
    question = pending_question or typed_question

    if question:
        user_message = {
            "id": len(st.session_state.chat_messages),
            "role": "user",
            "content": question,
        }
        st.session_state.chat_messages.append(user_message)
        with st.chat_message("user"):
            st.write(question)

        with st.status(
            "Agent is working on your question...", expanded=True
        ) as status_box:
            try:
                chat_response = None
                for event in stream_chat_question(
                    st.session_state.session_id, question
                ):
                    event_type = event.get("type")
                    if event_type == "step":
                        st.write(str(event.get("message", "Agent step completed.")))
                    elif event_type == "trace":
                        trace = event.get("trace", {})
                        if isinstance(trace, dict):
                            st.write(f"Completed: {_trace_title(trace)}")
                    elif event_type == "final":
                        chat_response = event.get("response")
                    elif event_type == "error":
                        raise RuntimeError(
                            str(event.get("message", "Chat request failed."))
                        )
                if not isinstance(chat_response, dict):
                    raise RuntimeError("Chat stream ended without a final response.")
            except httpx.HTTPStatusError as exc:
                content = exc.response.json().get("detail", "Chat request failed.")
                status_box.update(
                    label="Question analysis failed.",
                    state="error",
                    expanded=True,
                )
                assistant_message = {
                    "id": len(st.session_state.chat_messages),
                    "role": "assistant",
                    "content": content,
                }
            except httpx.RequestError:
                status_box.update(
                    label="Question analysis failed.",
                    state="error",
                    expanded=True,
                )
                assistant_message = {
                    "id": len(st.session_state.chat_messages),
                    "role": "assistant",
                    "content": (
                        "Could not reach the backend. If this is a hosted demo, "
                        "the API may be waking up. Please wait a moment and retry."
                    ),
                }
            except RuntimeError as exc:
                status_box.update(
                    label="Question analysis failed.",
                    state="error",
                    expanded=True,
                )
                assistant_message = {
                    "id": len(st.session_state.chat_messages),
                    "role": "assistant",
                    "content": str(exc),
                }
            else:
                tool_trace = chat_response.get("tool_trace") or []
                if not tool_trace:
                    st.write(
                        "Completed response composition without a pandas tool call."
                    )
                status_box.update(
                    label="Question analysis completed.",
                    state="complete",
                    expanded=False,
                )
                assistant_message = {
                    "id": len(st.session_state.chat_messages),
                    "role": "assistant",
                    "content": chat_response["answer"],
                    "table": chat_response.get("table"),
                    "chart_spec": chat_response.get("chart_spec"),
                    "tool_trace": tool_trace,
                    "clarification_options": chat_response.get("clarification_options"),
                }

        st.session_state.chat_messages.append(assistant_message)
        with st.chat_message("assistant"):
            st.write(assistant_message["content"])
            render_chat_artifacts(
                assistant_message, message_index=int(assistant_message["id"])
            )


# ═══════════════════════════════════════════════════════════════════════════════
# SHARED HELPERS
# ═══════════════════════════════════════════════════════════════════════════════


def _dashboard_insight_items(
    auto_analysis: dict[str, object], suggestions: dict[str, object]
) -> list[str]:
    items: list[str] = []
    gemini_insights = suggestions.get("insights", [])

    if gemini_insights:
        # If we have AI-generated insights, use them exclusively
        items.extend(str(item) for item in gemini_insights[:6])
    else:
        # Fallback to mechanical insights if AI failed
        numeric = auto_analysis.get("numeric_highlights", [])
        if numeric:
            item = numeric[0]
            items.append(
                f"{item.get('column')} has the widest numeric range: "
                f"{item.get('min')} to {item.get('max')}."
            )

        categorical = auto_analysis.get("categorical_highlights", [])
        if categorical:
            item = categorical[0]
            items.append(
                f"{item.get('column')} is led by \"{item.get('top_value')}\" "
                f"at about {item.get('percent')}% of rows."
            )

        correlations = auto_analysis.get("correlation_highlights", [])
        if correlations:
            item = correlations[0]
            items.append(
                f"Strongest numeric relationship found: {item.get('column_a')} vs "
                f"{item.get('column_b')} (r={item.get('correlation')})."
            )

    return _dedupe_texts(items)[:6]


def _render_dataset_analysis_activity(
    auto_analysis: dict[str, object], profile: dict[str, object]
) -> None:
    overview = auto_analysis.get("overview", {})
    quality = auto_analysis.get("data_quality", {})
    numeric = auto_analysis.get("numeric_highlights", [])
    categorical = auto_analysis.get("categorical_highlights", [])
    correlations = auto_analysis.get("correlation_highlights", [])
    charts = auto_analysis.get("recommended_charts", [])

    rows = overview.get("rows", profile.get("rows", 0))
    columns = overview.get("columns", profile.get("columns", 0))
    missing_cells = quality.get("total_missing_cells", 0)
    missing_columns = quality.get("columns_with_missing", 0)

    steps = [
        f"Loaded {rows} rows and {columns} columns.",
        f"Checked missing values: {missing_cells} missing cells across {missing_columns} columns.",
        f"Summarized {len(numeric)} numeric columns for spread, outliers, and range.",
        f"Ranked {len(categorical)} categorical columns by dominant values.",
    ]
    if correlations:
        strongest = correlations[0]
        steps.append(
            "Found strongest numeric relationship: "
            f"{strongest.get('column_a')} vs {strongest.get('column_b')} "
            f"(r={strongest.get('correlation')})."
        )
    else:
        steps.append("Checked numeric relationships; no strong pair was available.")
    steps.append(f"Prepared {len(charts)} chart recommendations for this dataset.")

    for index, step in enumerate(steps, start=1):
        st.markdown(f"**{index}. {step}**")


def render_agent_activity(tool_trace: list[dict[str, object]]) -> None:
    if not tool_trace:
        return
    st.write("Agent activity")
    for index, trace in enumerate(tool_trace, start=1):
        st.markdown(f"**{index}. {_trace_title(trace)}**")
        detail = _trace_detail(trace)
        if detail:
            st.caption(detail)


def _trace_title(trace: dict[str, object]) -> str:
    source = str(trace.get("source", "agent"))
    status = str(trace.get("status", ""))
    tool_name = trace.get("tool_name")
    if source == "guardrails":
        return "Checked request safety"
    if source == "router":
        if tool_name:
            return f"Router selected `{tool_name}`"
        return "Router evaluated the question"
    if source in {"llm", "gemini"}:
        if status == "skipped":
            return "Skipped LLM fallback"
        if tool_name:
            return f"LLM planner selected `{tool_name}`"
        return "LLM fallback evaluated the request"
    if source == "tool_validation":
        return f"Validated `{tool_name}` arguments"
    if source == "tool_executor":
        return f"Executed `{tool_name}`"
    if source == "agent_column_resolver":
        return "Resolved column names"
    if source == "agent_repair":
        return "Repaired tool arguments"
    if source == "agent_validation":
        return "Checked agent-specific constraints"
    if source == "memory":
        return "Used clarification memory"
    return source.replace("_", " ").title()


def _trace_detail(trace: dict[str, object]) -> str:
    message = str(trace.get("message") or "")
    confidence = trace.get("confidence")
    arguments = trace.get("arguments")
    parts = []
    if message:
        parts.append(message)
    if confidence is not None:
        parts.append(f"confidence={confidence}")
    if isinstance(arguments, dict) and arguments:
        compact_args = ", ".join(
            f"{key}={value}" for key, value in list(arguments.items())[:4]
        )
        parts.append(f"args: {compact_args}")
    return " | ".join(parts)


def _dedupe_texts(items: list[str]) -> list[str]:
    seen = set()
    result = []
    for item in items:
        cleaned = item.strip()
        key = cleaned.lower()
        if not cleaned or key in seen:
            continue
        seen.add(key)
        result.append(cleaned)
    return result


def render_chat_artifacts(
    message: dict[str, object], message_index: int | None = None
) -> None:
    message_id = message.get("id") or message_index or "current"
    if message.get("table"):
        st.dataframe(pd.DataFrame(message["table"]), use_container_width=True)
    if message.get("chart_spec"):
        dataset_frame = st.session_state.get("dataset_frame")
        if isinstance(dataset_frame, pd.DataFrame):
            render_chart_spec(
                dataset_frame,
                message["chart_spec"],
                chart_key=f"chat-chart-{message_id}",
            )
        else:
            st.json(message["chart_spec"])
    if message.get("tool_trace"):
        with st.expander("Agent activity", expanded=True):
            render_agent_activity(message["tool_trace"])
            if st.checkbox("Show raw tool trace", key=f"raw-tool-trace-{message_id}"):
                st.json(message["tool_trace"])
